#!/bin/bash

SYSROOTS=("base" "desktop" "desktop-nvidia" "desktop-nvidia-open" "desktop-cx4" "desktop-zhaoxin" "desktop-arise"
	"livekit" "livekit-nvidia" "livekit-nvidia-open" "livekit-cx4" "livekit-zhaoxin" "livekit-arise")
