#!/bin/bash

RECIPE="$TOP"/recipes/livekit.lst
SCRIPTS_BOOTSTRAP=("scripts/livekit.sh")
# Copy the dracut module
SCRIPT_PREBOOTSTRAP="scripts/livekit-base-pre.bash"
# Install templates after bootstrapping
SCRIPT_POSTBOOTSTRAP="scripts/livekit-base-post.bash"
