#!/bin/bash
PKGS=("nvidia")
# FIXED: encountered a weird issue on overlayfs when 6 or more lowerdirs
# are stacked together.
# Using busybox mount to workaround the length limit.
OVERLAY_DEPS=("desktop-common" "desktop" "dkms-common" "driver-nvidia-common")
ADDITIONAL_SCRIPTS=(
	"$AOSCBOOTSTRAP/scripts/enable-nvidia-drivers.sh"
)
