#!/bin/bash
PKGS=("nvidia")
# FIXME: encountered a weird issue on overlayfs when 6 or more lowerdirs
# are stacked together.
# DEPS=("desktop-common" "desktop" "dkms-common" "driver-nvidia-common")
DEPS=("desktop-common" "desktop" "dkms-common")
ADDITIONAL_SCRIPTS=(
	"$AOSCBOOTSTRAP/scripts/enable-nvidia-drivers.sh"
)
