#!/bin/bash

# NOTE: Encountered a strange issue on overlayfs when we have (equal
# or more than) 6 lower directories.
# The stack limit is 500, see fs/overlayfs/params.h.
# OVERLAY_DEP=("base" "desktop-common" "desktop" "dkms-common" "driver-nvidia-common" "driver-nvidia")
OVERLAY_DEP=("base" "desktop-common" "desktop" "dkms-common" "driver-nvidia")
